create table public."Animais" (
  id bigint generated by default as identity not null,
  "Timestamp" timestamp without time zone not null,
  "Especie" character varying null,
  "Idade" character varying null,
  "Ferido" boolean null,
  "Endereco" text null,
  "Descricao" text null,
  "Id_Usuario" uuid null default gen_random_uuid (),
  "Id_Empresa" uuid null,
  mensagens_empresa text null,
  "Em_Atendimento" boolean null default false,
  finalizado boolean null,
  constraint Animais_pkey primary key (id)
) TABLESPACE pg_default;

create table public.empresas (
  id uuid not null default extensions.uuid_generate_v4 (),
  nome text not null,
  cnpj text not null,
  email text not null,
  telefone text not null,
  estado text not null,
  cidade text not null,
  cep text not null,
  endereco text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  aprovacao text null,
  senha_hash text null,
  arquivo_zip_url text null,
  pasta_arquivo text null,
  motivo_recusa text null,
  constraint empresas_pkey primary key (id),
  constraint empresas_cnpj_key unique (cnpj),
  constraint empresas_email_key unique (email)
) TABLESPACE pg_default;

create table public.usuarios (
  id uuid not null default extensions.uuid_generate_v4 (),
  nome text not null,
  cpf text not null,
  email text not null,
  telefone text not null,
  estado text not null,
  cidade text not null,
  cep text not null,
  endereco text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  senha_hash text null,
  "tipoUsuario" text null,
  empresa_id uuid null,
  constraint cidadaos_pkey primary key (id),
  constraint cidadaos_cpf_key unique (cpf),
  constraint cidadaos_email_key unique (email),
  constraint usuarios_empresa_id_fkey foreign KEY (empresa_id) references empresas (id)
) TABLESPACE pg_default;
